Add new consignment configuration parameters
ncsu-landscape-dynamics/popsborder pull request #140
Opened 2021-11-12 20:29 UTC by kellynm

Added generation_method and file_type as configuration parameters to improve clarity of the consignment generation options. Rearranged the config file hierarchy to separate parameter-based generation parameters from input fule parameters.

2021-11-15 13:16 UTC, kellynm commented
@wenzeslaus I think this added configuration parameter to explicitly set the consignment generation method will improve clarity for user. Please let me know what you think.
Also, the linting test is failing related to yaml loader. I couldn't figure out how to fix. Could you check it and let me know what changes are needed?

2021-11-15 18:07 UTC, wenzeslaus commented
> the linting test is failing related to yaml loader. I couldn't figure out how to fix. Could you check it and let me know what changes are needed?

It seems a new version of Pylint added that warning. The code is unrelated to your changes, but you can fix that by adding the following to the lines from the error message:

```python
# pylint: disable=no-value-for-parameter
```

So the whole thing will look like,

for line 389 in `popsborder/simulation.py`:

```python
    return yaml.load(text)  # pylint: disable=no-value-for-parameter
```

and for line 409:

```python
        return yaml.load(open(filename))  # pylint: disable=no-value-for-parameter
```

We can disable them, because it is a fallback code for older versions of PyYAML (and the new code is addressing the issue the warning is trying to raise).

2021-11-15 18:53 UTC, wenzeslaus requested changes
This is great. I agree it makes the interface more clear and it fits how we organize other values in the configuration. The documentation improved as well.

There is a lot of unrelated changes in newlines in the notebooks and CSV files, but they are all in the right direction (`\r\n` to just `\n` and adding end of line at the end of file, i.e., generally more universal Unix style), so I'm happy to include it. Just mention that in the final commit message during merge.

My only major comment is about the in documentation. The other two are just stylistic.

2021-11-15 18:53 UTC, wenzeslaus commented on docs/consignments.md
> + file.
The leading space coming from the original text is just a typo as far as I can tell.

2021-11-16 13:33 UTC, kellynm commented on docs/consignments.md
> +further settings might be added. For example, F280 and AQIM inspections records
I think this is just a mistake. It was written in the documentation already and I just rearranged it. I'll remove that statement.

2021-11-16 14:43 UTC, merged