popsborder install instructions for conda on Windows
ncsu-landscape-dynamics/popsborder pull request #150
Opened 2022-01-25 19:30 UTC by arielsaffer

2022-01-25 21:10 UTC, wenzeslaus requested changes
Thank you. This looks good. I'm not sure how to resolve the tension between miniconda and the need for notebooks, but I would leave it as is here. I'm mainly concerned with the list of packages now.

2022-01-25 21:10 UTC, wenzeslaus commented on docs/conda_windows_install.md
> +```
The Super-Linter wants to know the language of the code block here.  I'm not sure what is appropriate for Windows command line. Maybe `bat` is okay here (we render it on GitHub, so their [Batchfile](https://github.com/github/linguist/blob/73e2d735c3c26577fc89c1cb3f8342e5a8ff1d82/lib/linguist/languages.yml#L484) category should apply).

The syntax is:

````
```bat
conda...
```
````

```
 /github/workspace/docs/conda_windows_install.md:11 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]]
```

2022-01-30 21:13 UTC, arielsaffer commented on docs/conda_windows_install.md
> +conda create --name popsborder_env python=3.8 pytest pylint flake8 black matplotlib seaborn pyyaml git pip
That makes sense! I updated the package list/Python version accordingly. Re-the above comment, I added a line to install jupyterlab, which I think should be enough to use notebooks from Anacaonda Prompt.

2022-02-08 14:53 UTC, wenzeslaus approved these changes
Great. Thank you!

2022-02-08 14:54 UTC, merged