basic excel import - export example
ncsu-landscape-dynamics/popsborder pull request #188
Opened 2022-04-10 17:25 UTC by arielsaffer

Here's a basic version of the example notebooks demonstrating the Excel import and export options. I used the simple format (not the "user friendly" one). Let me know if there's anything that would be useful to add.

2022-04-11 18:39 UTC, wenzeslaus requested changes
I'm not sure if we need example of output file in the documentation. Maybe makes sense when the notebook is computed?

2022-04-11 18:39 UTC, wenzeslaus commented on examples/notebooks/run_from_xlsx.ipynb
> +    "# PoPS Border simulation using XLSX file upload\n",
XLSX file configuration? (there can be couple different XLSX files involved)

2022-04-11 18:39 UTC, wenzeslaus commented on examples/notebooks/run_from_xlsx.ipynb
> +    "1. [consignments](../../docs/consignments.md) (what is imorted, from where, in what amounts), \n",
imported

2022-04-11 18:39 UTC, wenzeslaus commented on examples/notebooks/run_from_xlsx.ipynb
> +    "The summary of results can also be converted to a tabular format and exported to Excel, or used further in Python with the pandas library."
Consider adding headings. One e.g. here.

2022-04-11 18:41 UTC, wenzeslaus commented on examples/notebooks/run_from_xlsx.ipynb
> +    "There is a help file (linked above) for each of these sections that goes into greater detail about how to define the parameters."
Maybe also include text before every code cell describing the step. The two following code cells can be one introduced in a separate paragraph here as _Now we load the configuration from a file:_ or something like that.

2022-04-11 21:44 UTC, arielsaffer commented
I've tried to address all of your comments in this new version.

2022-04-12 21:30 UTC, wenzeslaus approved these changes

2022-04-12 21:32 UTC, merged

2022-04-12 21:33 UTC, wenzeslaus commented
Thanks, looks great, merged.